kind: pipeline
name: recovery-test

steps:
- name: build
  failure: ignore
  image: ubuntu:rolling
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - bash ./.drone.sh
  - tail -300 build_log.txt
