kind: pipeline
name: recovery-test

steps:
- name: build
  failure: ignore
  image: ubuntu:rolling
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - bash ./.drone.sh
  - cat build_log.txt | tail -300
  - date
