kind: pipeline
name: recovery-test

steps:
- name: build
  failure: ignore
  image: ubuntu:rolling
  environment:
    DEBIAN_FRONTEND: noninteractive
    YAUSER:
      from_secret: YAUSER
    YAPASS:
      from_secret: YAPASS
  commands:
  - bash ./.drone.sh
