kind: pipeline
name: recovery-test

steps:
- name: build
  image: ubuntu:rolling
  environment:
    DEBIAN_FRONTEND: noninteractive
  commands:
  - bash ./.drone.sh
- name: show log
  image: ubuntu:rolling
  commands:
  - cat build_log.txt | tail -300
  - date
  when:
    status:
    - failure
